import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { VideosProvider } from '@/lib/videosContext';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <VideosProvider>
          <Header />
          <main className="flex min-h-screen flex-col items-center p-4 md:p-24">
            {children}
          </main>
          <Toaster />
        </VideosProvider>
      </body>
    </html>
  );
}
